# VAE Training

In [1]:
import os, datetime
import numpy as np
import joblib
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer,text_to_word_sequence

## Collect HTML files

Load the HTML files

In [2]:
files = []

for f in os.listdir(os.path.join(os.getcwd(),'html')):
    fd = open(os.path.join(os.getcwd(),'html',f),'r')
    content = fd.read()
    files.append(content)
    fd.close()

Add a mock file as a concatentation of a previous one

In [3]:
files.append(files[0]*10)

## Preprocess the files

Define the padding and trimming parameters

In [4]:
padding='post'

maxlen=200
truncating='post'

Load the tokenizer

In [5]:
SQLi_tokenizer = joblib.load('ignore_tokenizer_20210318105336141483')

Convert the pages into token sequences:

In [6]:
tokens_list = SQLi_tokenizer.texts_to_sequences(files)

Pad and trim the sequences to fit them into an array:

In [7]:
tokens_array = keras.preprocessing.sequence.pad_sequences(tokens_list, padding=padding, maxlen=maxlen, truncating=truncating)

## Defining VAE

Instantiating a VAE module built following [https://keras.io/examples/generative/vae/](https://keras.io/examples/generative/vae/).

*Sampling layer with reparametrization trick* $z_i\sim\mathcal{N}(\mu_\phi, \sigma_\phi)$

In [8]:
class Sampling(layers.Layer):
    
    def call(self,inputs):
        z_mean, z_log_var = inputs
        batch = tf.shape(z_mean)[0]
        dim = tf.shape(z_mean)[1]
        epsilon = tf.keras.backend.random_normal(shape=(batch,dim))
        return z_mean + tf.exp(.5 * z_log_var) * epsilon

*Encoder* $Q_\phi(z \vert x)$

In [9]:
latent_dim = 2

encoder_inputs = keras.Input(shape=(200,))

x = layers.Dense(100,activation='relu')(encoder_inputs)
x = layers.Dense(25,activation='relu')(x)
z_mean = layers.Dense(latent_dim, name='z_mean')(x)
z_log_var = layers.Dense(latent_dim, name='z_log_var')(x)
z = Sampling()([z_mean,z_log_var])
encoder = keras.Model(encoder_inputs, [z_mean,z_log_var,z], name='encoder')
encoder.summary()

Model: "encoder"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 200)]        0                                            
__________________________________________________________________________________________________
dense (Dense)                   (None, 100)          20100       input_1[0][0]                    
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 25)           2525        dense[0][0]                      
__________________________________________________________________________________________________
z_mean (Dense)                  (None, 2)            52          dense_1[0][0]                    
____________________________________________________________________________________________

*Decoder* $P_\theta(x\vert z)$

In [10]:
latent_inputs = keras.Input(shape=(latent_dim,))

x = layers.Dense(25,activation='relu')(latent_inputs)
x = layers.Dense(100,activation='relu')(x)
decoder_outputs = layers.Dense(200,activation='relu')(x)

decoder = keras.Model(latent_inputs, decoder_outputs, name='decoder')
decoder.summary()

Model: "decoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 2)]               0         
_________________________________________________________________
dense_2 (Dense)              (None, 25)                75        
_________________________________________________________________
dense_3 (Dense)              (None, 100)               2600      
_________________________________________________________________
dense_4 (Dense)              (None, 200)               20200     
Total params: 22,875
Trainable params: 22,875
Non-trainable params: 0
_________________________________________________________________


*VAE with KL+reconstruction loss*

In [11]:
class VAE(keras.Model):
    def __init__(self,encoder,decoder,**kwargs):
        super(VAE,self).__init__(**kwargs)
        self.encoder = encoder
        self.decoder = decoder
        self.total_loss_tracker = keras.metrics.Mean(name='total_loss')
        self.reconstruction_loss_tracker = keras.metrics.Mean(name='reconstruction_loss')
        self.kl_loss_tracker = keras.metrics.Mean(name='kl_loss')
    
    @property
    def metrics(self):
        return [
            self.total_loss_tracker,
            self.reconstruction_loss_tracker,
            self.kl_loss_tracker,
        ]
    
    def train_step(self,data):
        with tf.GradientTape() as tape:
            z_mean, z_log_var, z = self.encoder(data)           
            reconstruction = self.decoder(z)
            print(reconstruction)
            reconstruction_loss = keras.losses.mean_squared_error(data,reconstruction)
            #reconstruction_loss = tf.reduce_sum(keras.losses.mean_squared_error(data,reconstruction), axis=1)
            kl_loss = -.5 * (1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var))
            kl_loss = (tf.reduce_sum(kl_loss,axis=1))
            total_loss = reconstruction_loss + kl_loss
        grads = tape.gradient(total_loss,self.trainable_weights)
        self.optimizer.apply_gradients(zip(grads,self.trainable_weights))
        self.total_loss_tracker.update_state(total_loss)
        self.reconstruction_loss_tracker.update_state(reconstruction_loss)
        self.kl_loss_tracker.update_state(kl_loss)
        return {
            'loss': self.total_loss_tracker.result(),
            'reconstruction_loss': self.reconstruction_loss_tracker.result(),
            'kl_loss': self.kl_loss_tracker.result(),
        }

## Training the VAE

Instantiating and training the model

In [12]:
vae = VAE(encoder,decoder)
vae.compile(optimizer=keras.optimizers.Adam())
vae.fit(tokens_array, epochs=2000, batch_size=3)

Epoch 1/2000
Tensor("decoder/dense_4/Relu:0", shape=(None, 200), dtype=float32)
Tensor("decoder/dense_4/Relu:0", shape=(None, 200), dtype=float32)
2/2 [==============================] - 0s 4ms/step - loss: 3804863.0833 - reconstruction_loss: 20915.4844 - kl_loss: 4303964.0000
Epoch 2/2000
2/2 [==============================] - 0s 4ms/step - loss: 349.1680 - reconstruction_loss: 283.2914 - kl_loss: 46.3449
Epoch 3/2000
2/2 [==============================] - 0s 3ms/step - loss: 363.4911 - reconstruction_loss: 282.7825 - kl_loss: 56.5070
Epoch 4/2000
2/2 [==============================] - 0s 6ms/step - loss: 314.8714 - reconstruction_loss: 282.4054 - kl_loss: 63.9185
Epoch 5/2000
2/2 [==============================] - 0s 2ms/step - loss: 372.1857 - reconstruction_loss: 282.4065 - kl_loss: 64.4420
Epoch 6/2000
2/2 [==============================] - 0s 3ms/step - loss: 368.0111 - reconstruction_loss: 282.5163 - kl_loss: 63.4596
Epoch 7/2000
2/2 [==============================] - 0s 3ms/step

2/2 [==============================] - 0s 3ms/step - loss: 249.6512 - reconstruction_loss: 189.4000 - kl_loss: 49.5331
Epoch 62/2000
2/2 [==============================] - 0s 3ms/step - loss: 217.7703 - reconstruction_loss: 185.3684 - kl_loss: 50.0867
Epoch 63/2000
2/2 [==============================] - 0s 3ms/step - loss: 245.3720 - reconstruction_loss: 182.7419 - kl_loss: 50.2154
Epoch 64/2000
2/2 [==============================] - 0s 3ms/step - loss: 210.0944 - reconstruction_loss: 179.5564 - kl_loss: 49.9695
Epoch 65/2000
2/2 [==============================] - 0s 4ms/step - loss: 207.5168 - reconstruction_loss: 177.2162 - kl_loss: 49.4968
Epoch 66/2000
2/2 [==============================] - 0s 3ms/step - loss: 236.1783 - reconstruction_loss: 175.2306 - kl_loss: 49.0139
Epoch 67/2000
2/2 [==============================] - 0s 3ms/step - loss: 202.5330 - reconstruction_loss: 172.9106 - kl_loss: 48.3035
Epoch 68/2000
2/2 [==============================] - 0s 3ms/step - loss: 230.6323 -

2/2 [==============================] - 0s 3ms/step - loss: 158.4858 - reconstruction_loss: 122.0195 - kl_loss: 24.0527
Epoch 123/2000
2/2 [==============================] - 0s 3ms/step - loss: 156.2263 - reconstruction_loss: 120.7295 - kl_loss: 24.2621
Epoch 124/2000
2/2 [==============================] - 0s 3ms/step - loss: 154.9944 - reconstruction_loss: 119.2270 - kl_loss: 24.3727
Epoch 125/2000
2/2 [==============================] - 0s 3ms/step - loss: 152.4332 - reconstruction_loss: 119.6848 - kl_loss: 24.1771
Epoch 126/2000
2/2 [==============================] - 0s 3ms/step - loss: 149.2647 - reconstruction_loss: 117.7781 - kl_loss: 24.2827
Epoch 127/2000
2/2 [==============================] - 0s 3ms/step - loss: 129.2548 - reconstruction_loss: 119.5246 - kl_loss: 23.9801
Epoch 128/2000
2/2 [==============================] - 0s 3ms/step - loss: 149.1230 - reconstruction_loss: 118.4371 - kl_loss: 23.3484
Epoch 129/2000
2/2 [==============================] - 0s 3ms/step - loss: 151

2/2 [==============================] - 0s 2ms/step - loss: 129.8190 - reconstruction_loss: 109.4140 - kl_loss: 11.6635
Epoch 183/2000
2/2 [==============================] - 0s 2ms/step - loss: 132.6527 - reconstruction_loss: 108.4746 - kl_loss: 11.9831
Epoch 184/2000
2/2 [==============================] - 0s 3ms/step - loss: 108.4200 - reconstruction_loss: 109.5350 - kl_loss: 11.8817
Epoch 185/2000
2/2 [==============================] - 0s 3ms/step - loss: 132.3055 - reconstruction_loss: 108.6214 - kl_loss: 11.5908
Epoch 186/2000
2/2 [==============================] - 0s 3ms/step - loss: 103.3179 - reconstruction_loss: 109.9971 - kl_loss: 10.9155
Epoch 187/2000
2/2 [==============================] - 0s 3ms/step - loss: 125.7669 - reconstruction_loss: 109.2719 - kl_loss: 10.7823
Epoch 188/2000
2/2 [==============================] - 0s 3ms/step - loss: 128.9223 - reconstruction_loss: 111.6383 - kl_loss: 10.5110
Epoch 189/2000
2/2 [==============================] - 0s 3ms/step - loss: 126

2/2 [==============================] - 0s 3ms/step - loss: 118.4012 - reconstruction_loss: 98.9678 - kl_loss: 7.6758
Epoch 244/2000
2/2 [==============================] - ETA: 0s - loss: 125.2958 - reconstruction_loss: 116.4383 - kl_loss: 8.857 - 0s 3ms/step - loss: 112.4392 - reconstruction_loss: 98.1175 - kl_loss: 7.8934
Epoch 245/2000
2/2 [==============================] - 0s 3ms/step - loss: 91.6369 - reconstruction_loss: 96.2749 - kl_loss: 8.2420
Epoch 246/2000
2/2 [==============================] - 0s 3ms/step - loss: 93.7291 - reconstruction_loss: 98.7880 - kl_loss: 8.2476
Epoch 247/2000
2/2 [==============================] - 0s 4ms/step - loss: 115.3701 - reconstruction_loss: 95.0464 - kl_loss: 8.7795
Epoch 248/2000
2/2 [==============================] - 0s 3ms/step - loss: 91.7586 - reconstruction_loss: 95.7480 - kl_loss: 9.3031
Epoch 249/2000
2/2 [==============================] - 0s 4ms/step - loss: 110.9642 - reconstruction_loss: 96.1110 - kl_loss: 8.7339
Epoch 250/2000
2/2

2/2 [==============================] - 0s 2ms/step - loss: 97.2418 - reconstruction_loss: 87.0357 - kl_loss: 5.3002
Epoch 305/2000
2/2 [==============================] - 0s 4ms/step - loss: 84.7164 - reconstruction_loss: 89.0609 - kl_loss: 5.0748
Epoch 306/2000
2/2 [==============================] - 0s 3ms/step - loss: 99.9905 - reconstruction_loss: 85.6818 - kl_loss: 5.4222
Epoch 307/2000
2/2 [==============================] - 0s 6ms/step - loss: 82.3327 - reconstruction_loss: 88.0102 - kl_loss: 6.0313
Epoch 308/2000
2/2 [==============================] - 0s 4ms/step - loss: 102.1894 - reconstruction_loss: 86.7526 - kl_loss: 6.5371
Epoch 309/2000
2/2 [==============================] - 0s 3ms/step - loss: 82.2564 - reconstruction_loss: 85.3185 - kl_loss: 6.6080
Epoch 310/2000
2/2 [==============================] - 0s 3ms/step - loss: 81.5816 - reconstruction_loss: 88.4989 - kl_loss: 6.0680
Epoch 311/2000
2/2 [==============================] - 0s 4ms/step - loss: 98.8395 - reconstructio

2/2 [==============================] - 0s 3ms/step - loss: 93.9882 - reconstruction_loss: 81.6088 - kl_loss: 4.8825
Epoch 366/2000
2/2 [==============================] - 0s 3ms/step - loss: 91.3350 - reconstruction_loss: 81.0739 - kl_loss: 5.1168
Epoch 367/2000
2/2 [==============================] - 0s 3ms/step - loss: 78.9860 - reconstruction_loss: 83.5084 - kl_loss: 5.3381
Epoch 368/2000
2/2 [==============================] - 0s 3ms/step - loss: 73.7132 - reconstruction_loss: 81.1219 - kl_loss: 5.4543
Epoch 369/2000
2/2 [==============================] - 0s 3ms/step - loss: 76.9012 - reconstruction_loss: 82.2921 - kl_loss: 5.4294
Epoch 370/2000
2/2 [==============================] - 0s 3ms/step - loss: 98.0246 - reconstruction_loss: 82.3823 - kl_loss: 5.3796
Epoch 371/2000
2/2 [==============================] - 0s 3ms/step - loss: 95.1491 - reconstruction_loss: 82.4795 - kl_loss: 5.4638
Epoch 372/2000
2/2 [==============================] - 0s 3ms/step - loss: 74.2202 - reconstruction

2/2 [==============================] - 0s 3ms/step - loss: 91.2664 - reconstruction_loss: 79.7498 - kl_loss: 4.9506
Epoch 428/2000
2/2 [==============================] - 0s 3ms/step - loss: 75.5546 - reconstruction_loss: 82.7445 - kl_loss: 5.3640
Epoch 429/2000
2/2 [==============================] - 0s 3ms/step - loss: 90.2346 - reconstruction_loss: 77.4943 - kl_loss: 5.1585
Epoch 430/2000
2/2 [==============================] - 0s 3ms/step - loss: 82.8775 - reconstruction_loss: 96.3409 - kl_loss: 4.4970
Epoch 431/2000
2/2 [==============================] - 0s 3ms/step - loss: 97.0134 - reconstruction_loss: 83.7452 - kl_loss: 4.4941
Epoch 432/2000
2/2 [==============================] - 0s 3ms/step - loss: 95.2481 - reconstruction_loss: 79.8678 - kl_loss: 5.7407
Epoch 433/2000
2/2 [==============================] - 0s 3ms/step - loss: 80.4905 - reconstruction_loss: 89.9630 - kl_loss: 7.1652
Epoch 434/2000
2/2 [==============================] - 0s 3ms/step - loss: 105.7744 - reconstructio

2/2 [==============================] - 0s 3ms/step - loss: 87.6762 - reconstruction_loss: 75.0271 - kl_loss: 4.7372
Epoch 490/2000
2/2 [==============================] - 0s 3ms/step - loss: 67.4054 - reconstruction_loss: 74.9871 - kl_loss: 4.8858
Epoch 491/2000
2/2 [==============================] - 0s 4ms/step - loss: 86.2430 - reconstruction_loss: 74.1560 - kl_loss: 5.0739
Epoch 492/2000
2/2 [==============================] - 0s 5ms/step - loss: 88.4837 - reconstruction_loss: 75.4895 - kl_loss: 5.0531
Epoch 493/2000
2/2 [==============================] - 0s 3ms/step - loss: 69.5534 - reconstruction_loss: 74.9131 - kl_loss: 4.9831
Epoch 494/2000
2/2 [==============================] - 0s 3ms/step - loss: 87.3382 - reconstruction_loss: 75.9800 - kl_loss: 4.8069
Epoch 495/2000
2/2 [==============================] - 0s 4ms/step - loss: 70.6875 - reconstruction_loss: 75.1913 - kl_loss: 4.5462
Epoch 496/2000
2/2 [==============================] - 0s 3ms/step - loss: 66.7168 - reconstruction

2/2 [==============================] - 0s 3ms/step - loss: 67.8749 - reconstruction_loss: 75.3110 - kl_loss: 5.1294
Epoch 552/2000
2/2 [==============================] - 0s 3ms/step - loss: 93.1966 - reconstruction_loss: 77.2260 - kl_loss: 4.9823
Epoch 553/2000
2/2 [==============================] - 0s 6ms/step - loss: 82.6984 - reconstruction_loss: 73.6555 - kl_loss: 4.6991
Epoch 554/2000
2/2 [==============================] - 0s 3ms/step - loss: 84.5322 - reconstruction_loss: 75.3137 - kl_loss: 4.4359
Epoch 555/2000
2/2 [==============================] - 0s 5ms/step - loss: 94.5208 - reconstruction_loss: 81.4323 - kl_loss: 4.2672
Epoch 556/2000
2/2 [==============================] - 0s 6ms/step - loss: 65.7041 - reconstruction_loss: 73.7942 - kl_loss: 4.9343
Epoch 557/2000
2/2 [==============================] - 0s 5ms/step - loss: 91.7602 - reconstruction_loss: 75.7096 - kl_loss: 5.1558
Epoch 558/2000
2/2 [==============================] - 0s 5ms/step - loss: 89.2309 - reconstruction

2/2 [==============================] - 0s 4ms/step - loss: 65.9974 - reconstruction_loss: 74.0754 - kl_loss: 5.0097
Epoch 614/2000
2/2 [==============================] - 0s 7ms/step - loss: 84.5051 - reconstruction_loss: 73.4079 - kl_loss: 4.7718
Epoch 615/2000
2/2 [==============================] - 0s 4ms/step - loss: 83.4649 - reconstruction_loss: 72.5495 - kl_loss: 4.4693
Epoch 616/2000
2/2 [==============================] - 0s 5ms/step - loss: 64.6768 - reconstruction_loss: 73.5532 - kl_loss: 4.2605
Epoch 617/2000
2/2 [==============================] - 0s 4ms/step - loss: 66.7258 - reconstruction_loss: 72.7753 - kl_loss: 4.2288
Epoch 618/2000
2/2 [==============================] - 0s 3ms/step - loss: 82.2497 - reconstruction_loss: 71.6597 - kl_loss: 4.3010
Epoch 619/2000
2/2 [==============================] - 0s 4ms/step - loss: 84.5239 - reconstruction_loss: 71.5773 - kl_loss: 4.3571
Epoch 620/2000
2/2 [==============================] - 0s 3ms/step - loss: 65.0187 - reconstruction

2/2 [==============================] - 0s 4ms/step - loss: 83.5702 - reconstruction_loss: 71.2349 - kl_loss: 5.2304
Epoch 676/2000
2/2 [==============================] - 0s 3ms/step - loss: 85.2169 - reconstruction_loss: 72.1466 - kl_loss: 5.2074
Epoch 677/2000
2/2 [==============================] - 0s 3ms/step - loss: 86.1548 - reconstruction_loss: 71.9305 - kl_loss: 5.0596
Epoch 678/2000
2/2 [==============================] - 0s 2ms/step - loss: 65.0612 - reconstruction_loss: 70.5460 - kl_loss: 4.8033
Epoch 679/2000
2/2 [==============================] - 0s 3ms/step - loss: 66.9412 - reconstruction_loss: 73.3729 - kl_loss: 4.5694
Epoch 680/2000
2/2 [==============================] - 0s 3ms/step - loss: 63.9615 - reconstruction_loss: 72.4877 - kl_loss: 4.6033
Epoch 681/2000
2/2 [==============================] - 0s 3ms/step - loss: 65.3871 - reconstruction_loss: 71.1090 - kl_loss: 4.7067
Epoch 682/2000
2/2 [==============================] - 0s 4ms/step - loss: 82.6782 - reconstruction

2/2 [==============================] - 0s 3ms/step - loss: 66.0768 - reconstruction_loss: 70.0856 - kl_loss: 5.2335
Epoch 735/2000
2/2 [==============================] - 0s 3ms/step - loss: 83.2253 - reconstruction_loss: 70.5963 - kl_loss: 5.1787
Epoch 736/2000
2/2 [==============================] - 0s 4ms/step - loss: 62.8793 - reconstruction_loss: 68.6865 - kl_loss: 4.9373
Epoch 737/2000
2/2 [==============================] - 0s 3ms/step - loss: 83.9592 - reconstruction_loss: 69.6258 - kl_loss: 4.8702
Epoch 738/2000
2/2 [==============================] - 0s 3ms/step - loss: 81.9453 - reconstruction_loss: 69.0540 - kl_loss: 4.7939
Epoch 739/2000
2/2 [==============================] - 0s 3ms/step - loss: 81.4743 - reconstruction_loss: 71.0842 - kl_loss: 4.6552
Epoch 740/2000
2/2 [==============================] - 0s 4ms/step - loss: 80.3206 - reconstruction_loss: 69.4635 - kl_loss: 4.9838
Epoch 741/2000
2/2 [==============================] - 0s 3ms/step - loss: 65.4105 - reconstruction

2/2 [==============================] - 0s 5ms/step - loss: 82.6726 - reconstruction_loss: 67.3512 - kl_loss: 5.2806
Epoch 797/2000
2/2 [==============================] - 0s 5ms/step - loss: 82.9344 - reconstruction_loss: 67.6163 - kl_loss: 5.1746
Epoch 798/2000
2/2 [==============================] - 0s 5ms/step - loss: 82.5643 - reconstruction_loss: 67.6661 - kl_loss: 5.0726
Epoch 799/2000
2/2 [==============================] - 0s 5ms/step - loss: 60.9713 - reconstruction_loss: 66.8629 - kl_loss: 5.0665
Epoch 800/2000
2/2 [==============================] - 0s 5ms/step - loss: 80.9483 - reconstruction_loss: 66.2777 - kl_loss: 5.0628
Epoch 801/2000
2/2 [==============================] - 0s 6ms/step - loss: 78.8642 - reconstruction_loss: 68.4713 - kl_loss: 4.9966
Epoch 802/2000
2/2 [==============================] - 0s 5ms/step - loss: 81.6378 - reconstruction_loss: 66.9948 - kl_loss: 5.0611
Epoch 803/2000
2/2 [==============================] - 0s 5ms/step - loss: 80.5560 - reconstruction

2/2 [==============================] - 0s 4ms/step - loss: 81.0807 - reconstruction_loss: 66.3331 - kl_loss: 5.5897
Epoch 859/2000
2/2 [==============================] - 0s 2ms/step - loss: 56.0774 - reconstruction_loss: 64.4284 - kl_loss: 5.8285
Epoch 860/2000
2/2 [==============================] - 0s 2ms/step - loss: 78.9802 - reconstruction_loss: 67.1995 - kl_loss: 5.6935
Epoch 861/2000
2/2 [==============================] - 0s 2ms/step - loss: 60.8262 - reconstruction_loss: 65.3704 - kl_loss: 5.6631
Epoch 862/2000
2/2 [==============================] - 0s 2ms/step - loss: 58.6740 - reconstruction_loss: 63.9016 - kl_loss: 5.6113
Epoch 863/2000
2/2 [==============================] - 0s 2ms/step - loss: 77.3653 - reconstruction_loss: 65.2755 - kl_loss: 5.6563
Epoch 864/2000
2/2 [==============================] - 0s 8ms/step - loss: 76.8027 - reconstruction_loss: 64.5006 - kl_loss: 5.6201
Epoch 865/2000
2/2 [==============================] - 0s 3ms/step - loss: 80.7780 - reconstruction

2/2 [==============================] - 0s 3ms/step - loss: 60.5349 - reconstruction_loss: 65.5699 - kl_loss: 5.9200
Epoch 921/2000
2/2 [==============================] - 0s 3ms/step - loss: 79.3841 - reconstruction_loss: 64.0970 - kl_loss: 5.8424
Epoch 922/2000
2/2 [==============================] - 0s 3ms/step - loss: 76.1867 - reconstruction_loss: 65.0009 - kl_loss: 6.0110
Epoch 923/2000
2/2 [==============================] - 0s 3ms/step - loss: 60.4747 - reconstruction_loss: 65.7923 - kl_loss: 5.9709
Epoch 924/2000
2/2 [==============================] - 0s 3ms/step - loss: 78.2284 - reconstruction_loss: 63.1011 - kl_loss: 5.9088
Epoch 925/2000
2/2 [==============================] - 0s 3ms/step - loss: 75.8121 - reconstruction_loss: 64.4960 - kl_loss: 5.7511
Epoch 926/2000
2/2 [==============================] - 0s 3ms/step - loss: 55.3701 - reconstruction_loss: 64.5226 - kl_loss: 5.7273
Epoch 927/2000
2/2 [==============================] - 0s 2ms/step - loss: 55.6611 - reconstruction

2/2 [==============================] - 0s 5ms/step - loss: 74.3682 - reconstruction_loss: 61.1060 - kl_loss: 6.2601
Epoch 983/2000
2/2 [==============================] - 0s 5ms/step - loss: 76.0296 - reconstruction_loss: 60.7685 - kl_loss: 6.0964
Epoch 984/2000
2/2 [==============================] - 0s 4ms/step - loss: 75.3245 - reconstruction_loss: 60.5180 - kl_loss: 5.9028
Epoch 985/2000
2/2 [==============================] - 0s 5ms/step - loss: 76.4092 - reconstruction_loss: 60.0941 - kl_loss: 5.7317
Epoch 986/2000
2/2 [==============================] - 0s 4ms/step - loss: 74.7947 - reconstruction_loss: 60.1864 - kl_loss: 5.5766
Epoch 987/2000
2/2 [==============================] - 0s 3ms/step - loss: 57.6549 - reconstruction_loss: 63.2786 - kl_loss: 5.4934
Epoch 988/2000
2/2 [==============================] - 0s 3ms/step - loss: 57.8790 - reconstruction_loss: 66.6322 - kl_loss: 5.3592
Epoch 989/2000
2/2 [==============================] - 0s 3ms/step - loss: 55.5524 - reconstruction

2/2 [==============================] - 0s 2ms/step - loss: 74.3882 - reconstruction_loss: 59.8625 - kl_loss: 5.7191
Epoch 1044/2000
2/2 [==============================] - 0s 2ms/step - loss: 70.9957 - reconstruction_loss: 59.7125 - kl_loss: 5.7671
Epoch 1045/2000
2/2 [==============================] - 0s 3ms/step - loss: 74.2159 - reconstruction_loss: 59.3712 - kl_loss: 5.8024
Epoch 1046/2000
2/2 [==============================] - 0s 3ms/step - loss: 71.8755 - reconstruction_loss: 59.1810 - kl_loss: 5.9725
Epoch 1047/2000
2/2 [==============================] - 0s 2ms/step - loss: 74.2421 - reconstruction_loss: 59.0581 - kl_loss: 6.2345
Epoch 1048/2000
2/2 [==============================] - 0s 2ms/step - loss: 74.4427 - reconstruction_loss: 58.9130 - kl_loss: 6.4169
Epoch 1049/2000
2/2 [==============================] - 0s 3ms/step - loss: 70.7643 - reconstruction_loss: 58.5824 - kl_loss: 6.5026
Epoch 1050/2000
2/2 [==============================] - 0s 3ms/step - loss: 54.6391 - reconst

2/2 [==============================] - 0s 5ms/step - loss: 81.2192 - reconstruction_loss: 60.5661 - kl_loss: 10.5252
Epoch 1106/2000
2/2 [==============================] - 0s 5ms/step - loss: 55.0080 - reconstruction_loss: 58.2902 - kl_loss: 9.8648
Epoch 1107/2000
2/2 [==============================] - 0s 5ms/step - loss: 54.6565 - reconstruction_loss: 59.2248 - kl_loss: 9.6759
Epoch 1108/2000
2/2 [==============================] - 0s 4ms/step - loss: 54.2415 - reconstruction_loss: 57.4010 - kl_loss: 9.4693
Epoch 1109/2000
2/2 [==============================] - 0s 5ms/step - loss: 71.4181 - reconstruction_loss: 55.7093 - kl_loss: 9.2621
Epoch 1110/2000
2/2 [==============================] - 0s 6ms/step - loss: 75.0384 - reconstruction_loss: 56.5159 - kl_loss: 9.4603
Epoch 1111/2000
2/2 [==============================] - 0s 5ms/step - loss: 75.2640 - reconstruction_loss: 56.9818 - kl_loss: 9.3569
Epoch 1112/2000
2/2 [==============================] - 0s 9ms/step - loss: 54.6443 - recons

2/2 [==============================] - 0s 4ms/step - loss: 49.0991 - reconstruction_loss: 53.8636 - kl_loss: 5.9500
Epoch 1166/2000
2/2 [==============================] - 0s 3ms/step - loss: 49.0346 - reconstruction_loss: 55.7516 - kl_loss: 5.8782
Epoch 1167/2000
2/2 [==============================] - 0s 3ms/step - loss: 67.9704 - reconstruction_loss: 54.0360 - kl_loss: 5.8804
Epoch 1168/2000
2/2 [==============================] - 0s 4ms/step - loss: 50.2296 - reconstruction_loss: 55.0787 - kl_loss: 5.8233
Epoch 1169/2000
2/2 [==============================] - 0s 5ms/step - loss: 68.2910 - reconstruction_loss: 53.9815 - kl_loss: 5.9594
Epoch 1170/2000
2/2 [==============================] - 0s 5ms/step - loss: 67.1175 - reconstruction_loss: 54.0780 - kl_loss: 6.0761
Epoch 1171/2000
2/2 [==============================] - 0s 4ms/step - loss: 68.4484 - reconstruction_loss: 53.9917 - kl_loss: 6.0259
Epoch 1172/2000
2/2 [==============================] - 0s 5ms/step - loss: 46.4610 - reconst

2/2 [==============================] - 0s 4ms/step - loss: 77.5022 - reconstruction_loss: 60.3830 - kl_loss: 8.4056
Epoch 1228/2000
2/2 [==============================] - 0s 4ms/step - loss: 72.3884 - reconstruction_loss: 55.8487 - kl_loss: 7.8395
Epoch 1229/2000
2/2 [==============================] - ETA: 0s - loss: 88.4729 - reconstruction_loss: 79.5310 - kl_loss: 8.942 - 0s 4ms/step - loss: 70.8472 - reconstruction_loss: 54.6562 - kl_loss: 7.3782
Epoch 1230/2000
2/2 [==============================] - ETA: 0s - loss: 27.6319 - reconstruction_loss: 22.0014 - kl_loss: 5.630 - 0s 4ms/step - loss: 52.3860 - reconstruction_loss: 57.6658 - kl_loss: 7.0973
Epoch 1231/2000
2/2 [==============================] - 0s 4ms/step - loss: 47.2915 - reconstruction_loss: 53.0225 - kl_loss: 7.3173
Epoch 1232/2000
2/2 [==============================] - 0s 3ms/step - loss: 47.7505 - reconstruction_loss: 51.7687 - kl_loss: 7.5103
Epoch 1233/2000
2/2 [==============================] - 0s 4ms/step - loss: 7

2/2 [==============================] - 0s 5ms/step - loss: 43.7408 - reconstruction_loss: 50.4048 - kl_loss: 5.8227
Epoch 1287/2000
2/2 [==============================] - 0s 4ms/step - loss: 63.3067 - reconstruction_loss: 50.6940 - kl_loss: 5.7998
Epoch 1288/2000
2/2 [==============================] - 0s 4ms/step - loss: 46.2036 - reconstruction_loss: 51.4671 - kl_loss: 5.6692
Epoch 1289/2000
2/2 [==============================] - 0s 3ms/step - loss: 45.9472 - reconstruction_loss: 51.2341 - kl_loss: 5.7457
Epoch 1290/2000
2/2 [==============================] - 0s 4ms/step - loss: 63.1610 - reconstruction_loss: 50.6563 - kl_loss: 5.8371
Epoch 1291/2000
2/2 [==============================] - 0s 4ms/step - loss: 62.6391 - reconstruction_loss: 49.8898 - kl_loss: 5.8070
Epoch 1292/2000
2/2 [==============================] - 0s 3ms/step - loss: 63.4042 - reconstruction_loss: 50.9415 - kl_loss: 5.7055
Epoch 1293/2000
2/2 [==============================] - 0s 4ms/step - loss: 63.2883 - reconst

2/2 [==============================] - 0s 5ms/step - loss: 44.4487 - reconstruction_loss: 49.6468 - kl_loss: 5.6517
Epoch 1349/2000
2/2 [==============================] - 0s 4ms/step - loss: 64.0836 - reconstruction_loss: 49.9596 - kl_loss: 5.7622
Epoch 1350/2000
2/2 [==============================] - 0s 4ms/step - loss: 43.8224 - reconstruction_loss: 49.2349 - kl_loss: 5.7198
Epoch 1351/2000
2/2 [==============================] - 0s 5ms/step - loss: 64.0149 - reconstruction_loss: 49.8254 - kl_loss: 5.6232
Epoch 1352/2000
2/2 [==============================] - 0s 6ms/step - loss: 63.0416 - reconstruction_loss: 50.9331 - kl_loss: 5.3578
Epoch 1353/2000
2/2 [==============================] - 0s 4ms/step - loss: 41.4594 - reconstruction_loss: 48.3868 - kl_loss: 5.3641
Epoch 1354/2000
2/2 [==============================] - 0s 5ms/step - loss: 42.6662 - reconstruction_loss: 49.3659 - kl_loss: 5.3972
Epoch 1355/2000
2/2 [==============================] - 0s 4ms/step - loss: 62.7562 - reconst

2/2 [==============================] - 0s 5ms/step - loss: 63.8162 - reconstruction_loss: 50.1864 - kl_loss: 5.1865
Epoch 1411/2000
2/2 [==============================] - 0s 3ms/step - loss: 61.8323 - reconstruction_loss: 48.4274 - kl_loss: 5.2698
Epoch 1412/2000
2/2 [==============================] - 0s 3ms/step - loss: 43.3447 - reconstruction_loss: 49.1474 - kl_loss: 5.4583
Epoch 1413/2000
2/2 [==============================] - 0s 8ms/step - loss: 63.8100 - reconstruction_loss: 49.6317 - kl_loss: 5.4137
Epoch 1414/2000
2/2 [==============================] - 0s 3ms/step - loss: 61.7817 - reconstruction_loss: 48.8701 - kl_loss: 5.2477
Epoch 1415/2000
2/2 [==============================] - 0s 9ms/step - loss: 63.8744 - reconstruction_loss: 50.4452 - kl_loss: 5.1811
Epoch 1416/2000
2/2 [==============================] - 0s 3ms/step - loss: 62.0305 - reconstruction_loss: 48.1700 - kl_loss: 5.3474
Epoch 1417/2000
2/2 [==============================] - 0s 3ms/step - loss: 41.1632 - reconst

2/2 [==============================] - 0s 3ms/step - loss: 60.0121 - reconstruction_loss: 47.0386 - kl_loss: 5.8883
Epoch 1473/2000
2/2 [==============================] - 0s 4ms/step - loss: 61.1176 - reconstruction_loss: 47.9291 - kl_loss: 5.7687
Epoch 1474/2000
2/2 [==============================] - 0s 4ms/step - loss: 61.3199 - reconstruction_loss: 46.9701 - kl_loss: 5.6761
Epoch 1475/2000
2/2 [==============================] - 0s 4ms/step - loss: 40.9439 - reconstruction_loss: 47.0811 - kl_loss: 5.4201
Epoch 1476/2000
2/2 [==============================] - 0s 4ms/step - loss: 59.4066 - reconstruction_loss: 46.8109 - kl_loss: 5.2784
Epoch 1477/2000
2/2 [==============================] - 0s 4ms/step - loss: 62.4433 - reconstruction_loss: 49.0284 - kl_loss: 5.1716
Epoch 1478/2000
2/2 [==============================] - 0s 5ms/step - loss: 41.4412 - reconstruction_loss: 47.6457 - kl_loss: 5.0376
Epoch 1479/2000
2/2 [==============================] - 0s 11ms/step - loss: 44.5359 - recons

2/2 [==============================] - 0s 4ms/step - loss: 61.1876 - reconstruction_loss: 47.3611 - kl_loss: 5.2386
Epoch 1534/2000
2/2 [==============================] - 0s 4ms/step - loss: 60.4130 - reconstruction_loss: 46.6965 - kl_loss: 5.1320
Epoch 1535/2000
2/2 [==============================] - 0s 5ms/step - loss: 41.1084 - reconstruction_loss: 47.6640 - kl_loss: 4.9689
Epoch 1536/2000
2/2 [==============================] - 0s 4ms/step - loss: 40.4082 - reconstruction_loss: 46.9646 - kl_loss: 4.9600
Epoch 1537/2000
2/2 [==============================] - 0s 5ms/step - loss: 40.2324 - reconstruction_loss: 47.9226 - kl_loss: 4.9709
Epoch 1538/2000
2/2 [==============================] - 0s 4ms/step - loss: 66.1013 - reconstruction_loss: 51.6662 - kl_loss: 5.0070
Epoch 1539/2000
2/2 [==============================] - 0s 5ms/step - loss: 59.3663 - reconstruction_loss: 46.6029 - kl_loss: 5.2834
Epoch 1540/2000
2/2 [==============================] - 0s 4ms/step - loss: 40.7486 - reconst

Epoch 1595/2000
2/2 [==============================] - 0s 4ms/step - loss: 60.2120 - reconstruction_loss: 46.3611 - kl_loss: 6.8495
Epoch 1596/2000
2/2 [==============================] - 0s 3ms/step - loss: 60.7343 - reconstruction_loss: 45.9321 - kl_loss: 6.8581
Epoch 1597/2000
2/2 [==============================] - 0s 6ms/step - loss: 40.3678 - reconstruction_loss: 45.8028 - kl_loss: 6.7272
Epoch 1598/2000
2/2 [==============================] - 0s 4ms/step - loss: 40.9824 - reconstruction_loss: 46.5327 - kl_loss: 6.6299
Epoch 1599/2000
2/2 [==============================] - 0s 3ms/step - loss: 62.2613 - reconstruction_loss: 46.8228 - kl_loss: 6.5287
Epoch 1600/2000
2/2 [==============================] - 0s 3ms/step - loss: 61.8755 - reconstruction_loss: 47.1440 - kl_loss: 6.4125
Epoch 1601/2000
2/2 [==============================] - 0s 3ms/step - loss: 42.6874 - reconstruction_loss: 48.8301 - kl_loss: 6.1310
Epoch 1602/2000
2/2 [==============================] - 0s 3ms/step - loss: 4

2/2 [==============================] - 0s 4ms/step - loss: 60.9604 - reconstruction_loss: 47.6314 - kl_loss: 6.4374
Epoch 1658/2000
2/2 [==============================] - 0s 5ms/step - loss: 42.3760 - reconstruction_loss: 46.7450 - kl_loss: 6.4982
Epoch 1659/2000
2/2 [==============================] - 0s 4ms/step - loss: 60.1925 - reconstruction_loss: 46.2928 - kl_loss: 6.5465
Epoch 1660/2000
2/2 [==============================] - 0s 4ms/step - loss: 60.5305 - reconstruction_loss: 46.1889 - kl_loss: 6.5274
Epoch 1661/2000
2/2 [==============================] - 0s 4ms/step - loss: 41.1740 - reconstruction_loss: 45.7869 - kl_loss: 6.3850
Epoch 1662/2000
2/2 [==============================] - 0s 5ms/step - loss: 60.1775 - reconstruction_loss: 46.1122 - kl_loss: 6.2581
Epoch 1663/2000
2/2 [==============================] - 0s 3ms/step - loss: 61.1574 - reconstruction_loss: 46.8929 - kl_loss: 6.0246
Epoch 1664/2000
2/2 [==============================] - 0s 3ms/step - loss: 61.3533 - reconst

2/2 [==============================] - 0s 5ms/step - loss: 58.8672 - reconstruction_loss: 46.2496 - kl_loss: 4.8212
Epoch 1720/2000
2/2 [==============================] - 0s 8ms/step - loss: 58.1175 - reconstruction_loss: 46.2346 - kl_loss: 4.8498
Epoch 1721/2000
2/2 [==============================] - 0s 5ms/step - loss: 59.9447 - reconstruction_loss: 46.9869 - kl_loss: 4.9142
Epoch 1722/2000
2/2 [==============================] - 0s 10ms/step - loss: 58.8228 - reconstruction_loss: 46.0338 - kl_loss: 4.8702
Epoch 1723/2000
2/2 [==============================] - 0s 3ms/step - loss: 38.9982 - reconstruction_loss: 46.2099 - kl_loss: 4.7608
Epoch 1724/2000
2/2 [==============================] - 0s 8ms/step - loss: 59.5356 - reconstruction_loss: 46.9952 - kl_loss: 4.8650
Epoch 1725/2000
2/2 [==============================] - 0s 3ms/step - loss: 57.9728 - reconstruction_loss: 45.8982 - kl_loss: 5.0338
Epoch 1726/2000
2/2 [==============================] - 0s 7ms/step - loss: 39.7901 - recons

2/2 [==============================] - 0s 3ms/step - loss: 58.1444 - reconstruction_loss: 45.3546 - kl_loss: 5.1814
Epoch 1782/2000
2/2 [==============================] - 0s 3ms/step - loss: 39.0663 - reconstruction_loss: 45.8872 - kl_loss: 5.1739
Epoch 1783/2000
2/2 [==============================] - 0s 8ms/step - loss: 38.4414 - reconstruction_loss: 45.5600 - kl_loss: 5.0907
Epoch 1784/2000
2/2 [==============================] - 0s 14ms/step - loss: 58.8431 - reconstruction_loss: 46.8534 - kl_loss: 4.9731
Epoch 1785/2000
2/2 [==============================] - 0s 2ms/step - loss: 58.0970 - reconstruction_loss: 46.1597 - kl_loss: 4.8829
Epoch 1786/2000
2/2 [==============================] - 0s 2ms/step - loss: 58.3861 - reconstruction_loss: 45.6361 - kl_loss: 4.9022
Epoch 1787/2000
2/2 [==============================] - 0s 2ms/step - loss: 58.3703 - reconstruction_loss: 46.4399 - kl_loss: 5.0100
Epoch 1788/2000
2/2 [==============================] - 0s 11ms/step - loss: 58.5832 - recon

2/2 [==============================] - 0s 8ms/step - loss: 65.5528 - reconstruction_loss: 48.4774 - kl_loss: 9.1567
Epoch 1844/2000
2/2 [==============================] - 0s 5ms/step - loss: 46.5469 - reconstruction_loss: 49.8146 - kl_loss: 8.8090
Epoch 1845/2000
2/2 [==============================] - 0s 9ms/step - loss: 44.1596 - reconstruction_loss: 46.9184 - kl_loss: 8.5118
Epoch 1846/2000
2/2 [==============================] - 0s 18ms/step - loss: 42.9265 - reconstruction_loss: 47.1611 - kl_loss: 8.1702
Epoch 1847/2000
2/2 [==============================] - 0s 6ms/step - loss: 63.3298 - reconstruction_loss: 46.4260 - kl_loss: 8.1098
Epoch 1848/2000
2/2 [==============================] - 0s 4ms/step - loss: 61.6483 - reconstruction_loss: 45.7482 - kl_loss: 7.9529
Epoch 1849/2000
2/2 [==============================] - 0s 5ms/step - loss: 41.9441 - reconstruction_loss: 45.1088 - kl_loss: 7.9400
Epoch 1850/2000
2/2 [==============================] - 0s 4ms/step - loss: 41.7550 - recons

2/2 [==============================] - 0s 12ms/step - loss: 58.3452 - reconstruction_loss: 44.5452 - kl_loss: 5.0169
Epoch 1906/2000
2/2 [==============================] - 0s 9ms/step - loss: 59.1516 - reconstruction_loss: 47.7914 - kl_loss: 4.7831
Epoch 1907/2000
2/2 [==============================] - 0s 6ms/step - loss: 42.4316 - reconstruction_loss: 51.8385 - kl_loss: 4.4696
Epoch 1908/2000
2/2 [==============================] - 0s 6ms/step - loss: 57.5019 - reconstruction_loss: 45.4540 - kl_loss: 5.0488
Epoch 1909/2000
2/2 [==============================] - 0s 7ms/step - loss: 65.6081 - reconstruction_loss: 50.5565 - kl_loss: 6.2301
Epoch 1910/2000
2/2 [==============================] - 0s 12ms/step - loss: 79.1593 - reconstruction_loss: 60.0320 - kl_loss: 7.7358
Epoch 1911/2000
2/2 [==============================] - 0s 6ms/step - loss: 43.0644 - reconstruction_loss: 48.0801 - kl_loss: 7.3049
Epoch 1912/2000
2/2 [==============================] - 0s 7ms/step - loss: 45.9828 - recon

2/2 [==============================] - 0s 7ms/step - loss: 66.9349 - reconstruction_loss: 47.8622 - kl_loss: 10.5358
Epoch 1968/2000
2/2 [==============================] - 0s 3ms/step - loss: 43.0968 - reconstruction_loss: 45.8515 - kl_loss: 9.9626
Epoch 1969/2000
2/2 [==============================] - 0s 4ms/step - loss: 42.7263 - reconstruction_loss: 46.4071 - kl_loss: 9.8860
Epoch 1970/2000
2/2 [==============================] - 0s 5ms/step - loss: 64.3026 - reconstruction_loss: 45.9142 - kl_loss: 10.0291
Epoch 1971/2000
2/2 [==============================] - 0s 7ms/step - loss: 43.0237 - reconstruction_loss: 45.4599 - kl_loss: 9.7347
Epoch 1972/2000
2/2 [==============================] - 0s 4ms/step - loss: 63.0499 - reconstruction_loss: 45.0791 - kl_loss: 9.8355
Epoch 1973/2000
2/2 [==============================] - 0s 4ms/step - loss: 63.9531 - reconstruction_loss: 44.9606 - kl_loss: 9.7742
Epoch 1974/2000
2/2 [==============================] - 0s 4ms/step - loss: 41.8406 - recon

## Checking the VAE

Printing the encoding of the first three data points (showing $\mu_\phi, \log\sigma_\phi, z$)

In [13]:
vae.encoder(tokens_array[0:3])

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.5895084 , -1.5412844 ],
        [-2.3142931 ,  0.31855693],
        [-1.3365623 , -2.065335  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-5.1746664, -2.7796502],
        [-2.2312315, -1.8900306],
        [-2.8823164, -1.1418735]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.537319  , -1.2586347 ],
        [-1.6780676 , -0.14333054],
        [-1.8338729 , -2.644469  ]], dtype=float32)>]

Computing the encoding and decoding of the first datapoint

In [14]:
xtilde = vae.decoder(vae.encoder(tokens_array[0:1]))

Rounding the computed representation to integers

In [15]:
xtilde_int = np.round(xtilde)

Printing the original and the reconstructed representation.

In [16]:
len(tokens_array[0])

200

In [17]:
tokens_array[0]

array([13, 14, 15, 16, 47,  4,  5, 10, 11, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 48, 12, 49, 12, 30, 31,  4,  5, 10, 11, 32, 33,
        6, 34, 35, 36,  6, 37,  7,  1,  8,  9, 38,  2,  3, 39,  7,  1,  8,
        9, 40,  2,  3, 41,  1, 42,  2, 43,  3, 44, 45, 46,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int32)

In [18]:
xtilde_int.shape

(1, 200)

In [19]:
xtilde_int

array([[13., 14., 15., 16., 46.,  4.,  5., 13., 11., 17., 18., 19., 20.,
        21., 22., 23., 24., 25., 26., 27., 28., 28., 47., 11., 46., 12.,
        29., 31.,  4.,  6., 11.,  0., 31., 31.,  8., 34., 32., 35.,  6.,
        35.,  7.,  0.,  9.,  9., 36.,  0.,  3., 37.,  7.,  0., 12.,  9.,
        37.,  0.,  0., 39.,  0., 41.,  0., 36.,  0., 41.,  0., 44.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.

In [20]:
SQLi_tokenizer.sequences_to_texts(tokens_array[0:1])

['<!-- saved from url= 0042 http://jabba hackingarena no:806/index php --> <html><head><meta http-equiv= Content-Type content= text/html charset=UTF-8 ></head><body>Login as admin for the flag! <br>some content some content <form action= http://jabba hackingarena no:806/index php method= post > <table width= 100 > <tbody><tr><td>Name:</td> <td><input type= text name= username value= ></td></tr> <tr><td>Password:</td> <td><input type= text name= passwd value= ></td></tr> <tr><td><input type= submit value= Submit ></td></tr> </tbody></table> </form> </body></html>']

In [21]:
SQLi_tokenizer.sequences_to_texts(xtilde_int)

['<!-- saved from url= </body></html> http://jabba hackingarena <!-- php --> <html><head><meta http-equiv= Content-Type content= text/html charset=UTF-8 ></head><body>Login as admin for the the 0042 php </body></html> content flag! action= http://jabba > php action= action= text <table method= width= > width= <td><input name= name= 100 ></td></tr> <tbody><tr><td>Name:</td> <td><input content name= <tbody><tr><td>Name:</td> <tr><td>Password:</td> <tr><td><input 100 <tr><td><input </tbody></table>']

In [22]:
np.mean(xtilde_int==tokens_array[0])

0.825

## Saving the VAE

Saving the model weights

In [23]:
timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S%f")
vae.save_weights('ignore_vae_W_'+timestamp)

Loading the model weights

In [24]:
vae1 = VAE(encoder,decoder)
vae1.load_weights('ignore_vae_W_'+timestamp)

Checking the weights

In [25]:
vae.decoder(vae.encoder(tokens_array[0:1])) == vae1.decoder(vae.encoder(tokens_array[0:1]))

<tf.Tensor: shape=(1, 200), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  